# Generated by Django 4.2.7 on 2023-11-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BioterioID', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_animal', models.CharField(choices=[('lactante', 'Lactante'), ('adulto', 'Adulto'), ('gestante', 'Gestante')], default='adulto', max_length=8, verbose_name='Estado del Animal')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioterioID.animal', verbose_name='ID Animal')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalInvestigacion',
            fields=[
                ('animallab_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BioterioLab.animallab')),
                ('fecha_destete', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Destete')),
            ],
            options={
                'verbose_name': 'Investigación',
                'verbose_name_plural': 'Investigación',
            },
            bases=('BioterioLab.animallab',),
        ),
        migrations.CreateModel(
            name='AnimalProduccion',
            fields=[
                ('animallab_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BioterioLab.animallab')),
                ('fecha_produccion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Producción')),
                ('peso_gramos_produccion', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso en gramos')),
                ('medidas_cm_produccion', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Medidas en cm')),
                ('consumo_alimento_gramos_produccion', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Alimentos en gramos')),
                ('consumo_agua_ml_produccion', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Agua en ml')),
                ('tipo_nacimiento', models.CharField(choices=[('natural', 'Parto Natural'), ('in vitro', 'In Vitro')], default='natural', max_length=8, verbose_name='Tipo de Nacimiento')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producción',
            },
            bases=('BioterioLab.animallab',),
        ),
    ]
