# Generated by Django 4.2.7 on 2023-11-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BioterioID', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Registro')),
                ('peso_gramos_registro', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso en gramos')),
                ('medidas_cm_registro', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Medidas en cm')),
                ('consumo_alimento_gramos_registro', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Alimentos en gramos')),
                ('consumo_agua_ml_registro', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Agua en ml')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioterioID.animal')),
            ],
            options={
                'verbose_name': 'Registro Diario',
                'verbose_name_plural': 'Registro Diario',
            },
        ),
        migrations.CreateModel(
            name='AnimalBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('por_parto', models.BooleanField(default=False, verbose_name='Por Parto')),
                ('por_cruce', models.BooleanField(default=False, verbose_name='Por Cruce')),
                ('separacion', models.BooleanField(default=False)),
                ('en_destete', models.BooleanField(default=False, verbose_name='En Destete')),
                ('fecha_destete_bio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Destete')),
                ('numero_crias_camada', models.IntegerField(blank=True, null=True, verbose_name='Número de Crías en Camada')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BioterioID.animal', verbose_name='ID Animal')),
            ],
            options={
                'verbose_name': 'Identificación Bitácora',
                'verbose_name_plural': 'Identificación Bitácora',
            },
        ),
    ]
