# Generated by Django 4.2.6 on 2023-11-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=50, unique=True)),
                ('tipo_animal', models.CharField(choices=[('rata', 'Rata'), ('raton', 'Ratón'), ('cobayo', 'Cobayo'), ('conejo', 'Conejo'), ('ave', 'Ave'), ('gato', 'Gato')], max_length=6)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('sepa', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('inicio_produccion', models.DateField()),
                ('peso_gramos', models.IntegerField()),
                ('longitud_cm', models.IntegerField()),
                ('numero_parto', models.IntegerField()),
                ('estado_vida', models.CharField(choices=[('vivo', 'Vivo'), ('muerto', 'Muerto')], max_length=6)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
