# Generated by Django 4.2.7 on 2023-11-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=4, unique=True, verbose_name='Número de Identificación')),
                ('tipo_animal', models.CharField(choices=[('rata', 'Rata'), ('raton', 'Ratón'), ('cobayo', 'Cobayo'), ('conejo', 'Conejo'), ('ave', 'Ave'), ('gato', 'Gato')], default='rata', max_length=6, verbose_name='Tipo de Animal')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='macho', max_length=6)),
                ('sepa', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('inicio_produccion', models.DateField(verbose_name='Inicio de Producción')),
                ('peso_gramos', models.IntegerField(verbose_name='Peso en gramos')),
                ('longitud_cm', models.IntegerField(verbose_name='Longitud en cm')),
                ('numero_parto', models.IntegerField(verbose_name='Número de Parto')),
                ('estado_vida', models.CharField(choices=[('vivo', 'Vivo'), ('muerto', 'Muerto')], default='vivo', max_length=6, verbose_name='Estado de Vida')),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Identificación',
                'verbose_name_plural': 'Identificación',
            },
        ),
    ]
